[tool.ruff]
target-version = "py312"

[tool.ruff.lint]
select = [
    "E", # pycodestyle
    "F", # pyflakes
    "UP", # pyupgrade,
    "B", # flake8-simplify
    "I", # isort
]

[tool.ruff.lint.pycodestyle]
max-line-length = 120

[tool.mypy]
python_version = "3.12"
disable_error_code = [
    "import", # check for an issue with imports
    "attr-defined", # check that attribute exists
]
check_untyped_defs = true
explicit_package_bases = true
files = ["src"]
