[tool.black]
target-version = ["py312"]

[tool.ruff]
target-version = "py312"

[tool.ruff.lint]
select = [
    "E", # pycodestyle
    "F", # pyflakes
    "UP", # pyupgrade,
    "B", # flake8-simplify
    "I", # isort
]

[tool.ruff.lint.pycodestyle]
max-line-length = 120

[tool.ruff.format]
quote-style = "double"

[tool.mypy]
python_version = "3.12"
disable_error_code = [
    "no-redef",
    "import",
    "attr-defined",
    "call-arg",
    "arg-type",
]
check_untyped_defs = true
